services:
    web:
        image: nginx:latest
        container_name: barber-api-nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/www
            - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
            - ./nginx/log:/var/log/nginx
        networks:
            - barber-api-network
    php:
        build: docker/
        container_name: barber-api-php
        restart: always
        volumes:
            - .:/www
        networks:
            - barber-api-network
        pull_policy: build
    db:
        container_name: barber-api-db
        image: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: barber-api
            MYSQL_DATABASE: barber-api
        ports:
            - 3306:3306
        volumes:
            - ./mysql-data:/var/lib/mysql
        networks:
            - barber-api-network
volumes:
    mysql-data:
networks:
    barber-api-network:
        driver: bridge
        name: barber-api-network
